//Exercise #1

When a Mule app starts, a connectivity test runs on components such as the HTTP or FTP connector that connect to an external server. The default behavior of the test logs a warning message and continues with the deployment instead of blocking it.

If the test fails, you can modify it by setting a number of reconnection attempts after an initial failure and forcing the deployment to fail when all connection attempts fail.

* Fail Deployment (`failsDeployment`): Forces the deployment to fail when the connection fails and all the configured reconnection attempts are exhausted.
* Reconnect (`reconnect`): Limits the number of reconnection attempts and the `frequency` between connection attempts. For example, you can set a count of 5 reconnection attempts at a `frequency` of every `4000` milliseconds (ms). The default is 2 reconnection attempts at a `frequency` of `2000ms`.
+
Example when the deployment fails after 5 reconnection attempts are exhausted:
+
[source,xml]
----
<http:request-config name="HTTP_Request_Config" doc:name="HTTP Request Config">
  <http:request-connection host="https://jsonplaceholder.typicode.com/posts" port="80">
    <reconnection failsDeployment="true">
      <reconnect frequency="4000" count="5"/>
    </reconnection>
  </http:request-connection>
</http:request-config>
----

* Reconnect Forever (`reconnect-forever`): Attempts to reconnect at a given `frequency`. The default `frequency` is every 2000 ms. No value for count is specified due to the unlimited number of attempts.
+
Example when the reconnection attempts are unlimited:
+
[source,xml]
----
<http:request-config name="HTTP_Request_Config" doc:name="HTTP Request Config">
<http:request-connection host="https://jsonplaceholder.typicode.com/posts" port="80" >
  <reconnection>
    <reconnect-forever frequency="4000"/>
  </reconnection>
</http:request-connection>
</http:request-config>
----
